name: "Load JSON as Environment Variables"
description: "Reads a JSON file and exports its keys as environment variables"
inputs:
  file:
    description: "Path to the JSON file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Read JSON and export variables
      shell: bash
      run: |
        set -e
        set -x
        pwd
        JSON_FILE=${{ inputs.file }}
        cat $JSON_FILE
        if [[ ! -f "$JSON_FILE" ]]; then
          echo "File not found: $JSON_FILE"
          exit 1
        fi
        for row in $(jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' $JSON_FILE); do
          echo "Exporting $row"
          echo "$row" >> $GITHUB_ENV
        done