name: Test Action on PR
run-name: "Test Action ${{((github.event_name == 'pull_request') && 'PR')}}"

# Triggers for the workflow
on:

  pull_request:
    branches:
      - 'dev'

jobs:
  test_oncall:
    uses: manuelqubika/test-github-actions/.github/workflows/action.yaml@main
    with:
      pr_branches: "['${{ github.head_ref }}', '${{ github.base_ref }}']"