name: Test Action on PR
run-name: "Test Action ${{((github.event_name == 'pull_request') && 'PR')}}"

# Triggers for the workflow
on:
  workflow_call:
    inputs:
      pr_branches:
        required: true
        default: ''
        type: string

  workflow_dispatch:
jobs: 
  branch_sel:
    name: Preprocessing
    runs-on: ubuntu-latest
    outputs:
      branch_array: ${{ inputs.pr_branches }}
    steps:
      - id: branch_selection
        run: 
          echo ${{ inputs.pr_branches }}

  run_test:
    name: test PR run
    runs-on: ubuntu-latest
    needs: branch_sel
    strategy:
      fail-fast: false
      matrix:
        branch:  ${{ fromJson(needs.branch_sel.outputs.branch_array) }}
    steps:
      - name: 'Cleanup'
      # Remove all files including hidden files, || true ensure that command returns success even when there is nothing to remove
        run: |
          printenv
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
          
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

