name: Run Script on PR Files

on:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      # Get changed files in the PR
      - name: Get list of changed files
        id: changed-files
        run: |
          # Get the list of files changed in the PR
          CHANGED_FILES=$(jq -r '.pull_request.files | .[].filename' < "${GITHUB_EVENT_PATH}")
          echo "${CHANGED_FILES}" > changed-files.txt
          echo "Changed files: ${CHANGED_FILES}"
          echo "::set-output name=files::$(cat changed-files.txt | tr '\n' ',')"

      # Run the script for each file
      - name: Run script for each file
        run: |
          # Read the changed files from the output
          for FILE in $(echo "${{ steps.changed-files.outputs.files }}" | tr ',' '\n'); do
            echo "Running script for file: $FILE"
            ./tools/formatter.sh "$FILE"
          done
