name: Test Action on PR
on:
  pull_request:

jobs:
  nda-auditor:
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      run: |
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: "run formatter"
      uses: ./.github/actions/format_check
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}