name: Run Matrix for Configs

on: [push]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: |
            files=$(find .github/configs -name '*.json' -exec basename {} \;)
            matrix=$(echo "$files" | jq -R . | jq -s .)
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
        shell: bash

  run-for-each-config:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Load env from ${{ matrix.config }}
        uses: ./.github/actions/load_config_file
        with:
          file: .github/configs/${{ matrix.config }}

      - name: Show loaded env
        run: |
          echo "ENV_1 is $ENV_1"
          echo "ENV_2 is $ENV_2"
          echo "ENV_3 is $ENV_3"

