name: Load Config from JSON

on: [push]

jobs:
  load-config-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load environment variables from config.json
        uses: ./.github/actions/load_config_file
        with:
          file: .github/configs/config.json

      - name: Use the environment variables
        run: |
          echo "ENV_1 is $ENV_1"
          echo "ENV_2 is $ENV_2"
          echo "ENV_3 is $ENV_3"
