name: Cherry Pick Validation

on:
  pull_request:

jobs:
  validate-cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Word Scan
        env:
          FAIL: false
        run: |
          set -x
          sleep 480
          if [ $FAIL == "true" ]; then
            exit 1
          else
            exit 0
          fi
  merge-pr:
    runs-on: ubuntu-latest
    needs: validate-cherry-pick
    env:
      QUBIKA_GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Merge PRs
        run: |
          python3 tools/merge_commit.py

