name: Cherry Pick Validation

on:
  pull_request:

jobs:
  validate-cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Word Scan
        env:
          FAIL: true
        run: |
          set -x
          if [ $FAIL == "true" ]; then
            exit 1
          else
            exit 0
          fi

